debugging (empty list)
- mistake: empty list means endpoint == -1. It should be initialized
there.

- Push function works normally, but after an item is popped, and the
user attempts to push another item in:
TypeError: 'str' object does not support item assignment